# Generated by Django 3.1.3 on 2021-01-08 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_keyword', models.CharField(max_length=100, null=True)),
                ('meta_keyword', models.TextField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('review_count', models.CharField(max_length=100, null=True)),
                ('buy_count', models.CharField(max_length=100, null=True)),
                ('registration_date', models.CharField(max_length=100, null=True)),
                ('dib_count', models.CharField(max_length=100, null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
    ]
